kind: Pod
apiVersion: v1
metadata: 
  name: debug
  namespace: expense
spec:
  containers:
  - name: debug
    image: devopskk/debug:v1.0

# alme OS - less commands, to get some required commands, wrote them in debug image in dockerhub. called it here
# So only those extra commands can be used in hub.