apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql # mysql component service name
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # deployment resource labels
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
  # pod defination
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: app
    spec:
      containers:
      - name: backend
        image: devopskk/backend:v1.0
        envFrom:
        - configMapRef:
            name: backend

# we will login as expense user, because we gave user expense in docker file in backend code pulling fromdocker hub.
# As we picked alpina OS,even curl command won't be working on in container. to make them work give them in DF.
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    project: expense
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080