apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql # mysql component service name
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # deployment resource labels
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
  # pod defination
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: app
    spec:
      # initContainers:
      # - name: init-myservice
      #   image: busybox:1.28
      #   command: ['sh', '-c', "until nslookup mysql; do echo waiting for myservice; sleep 2; done"] 
      containers:
      - name: backend
        image: devopskk/backend:v1.0
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "150m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 30
        envFrom:
        - configMapRef:
            name: backend

# we will login as expense user, because we gave user expense in docker file in backend code pulling fromdocker hub.
# As we picked alpina OS,even curl command won't be working on in container. to make them work give them in DF.
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    project: expense
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080