apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  # deployment resource labels
  labels:
    component: mysql
    project: expense
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
  # pod defination
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: devopskk/mysql:v1.0


kind: Service
apiVersion: v1
metadata:
  name: mysql
  name: expense
spec:
  selector:
    component: mysql
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306