apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  # deployment resource labels
  labels:
    component: mysql
    project: expense
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
  # pod defination
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: devopskk/mysql:v1.0
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "900m"
            memory: "500Mi"
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 100
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 100
          periodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    component: mysql
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #Target-port